### ISSUE TITLE
PiT 23.1: servlet container does not listen to 8181

### ISSUE THREAD

**Issue by manolo** [vaadin/base-starter-flow-karaf#100]
After https://github.com/vaadin/vaadin-flow-karaf-example/pull/99 sever does not listen to any port, but artifact seems deployed
```
[INFO] Building jar: /private/tmp/kk/vaadin-flow-karaf-example/main-ui/target/main-ui-1.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- karaf-maven-plugin:4.4.0:run (run) @ main-ui ---
[INFO] Extracting Karaf container
[INFO] Starting Karaf container
May 23, 2022 10:07:47 AM org.apache.karaf.main.Main launch
INFO: Installing and starting initial bundles
May 23, 2022 10:07:47 AM org.apache.karaf.main.Main launch
INFO: All initial bundles installed and set to start
May 23, 2022 10:07:47 AM org.apache.karaf.main.Main$KarafLockCallback lockAcquired
INFO: Lock acquired. Setting startlevel to 100
May 23, 2022 10:07:47 AM org.apache.karaf.main.ShutdownSocketThread run
INFO: Shutdown socket thread is listening on 127.0.0.1:65327
[INFO] Deploying features repository /private/tmp/kk/vaadin-flow-karaf-example/main-ui/target/feature/feature.xml
[INFO] Artifact deployed
```
### How to reproduce
- `git clone https://github.com/vaadin/vaadin-flow-karaf-example.git `
- `cd vaadin-flow-karaf-example`
- `mvn clean install`
- `mvn -B -pl main-ui install -Prun`
- Server never listen to `8181`

**Comment by mcollovati** [comment]
Shouldn't port be 8181?

**Comment by mshabarov** [comment]
Yes, it should be 8181. I got the following when navigate to `localhost:8181`
```
HTTP ERROR 404 Not Found
URI: /
STATUS: 404
MESSAGE: Not Found
SERVLET: org.apache.felix.http.base.internal.dispatch.DispatcherServlet-284a30a7
```

**Comment by mcollovati** [comment]
It seems to work, after waiting for a while. Or refreshing the page several times.
But not always

**Comment by mcollovati** [comment]
@mshabarov can you please try if the following configuration in `main-ui/pom.xml` works for you?

```
<featuresToInstall>pax-web-http-whiteboard,scr,spifly,${project.artifactId}</featuresToInstall>
```

Edit: websocket support does not work with this configuration

**Comment by mshabarov** [comment]
With the change you mentioned above, I got:
`There was an exception while trying to navigate to '' with the root cause 'java.lang.ClassNotFoundException: com.vaadin.flow.component.HasClearButton not found by com.vaadin.flow.server [145]'` - the same as in https://github.com/vaadin/base-starter-flow-osgi/issues/224 , so I guess 404 is solved by switching to the PAX Web.

We should't sacrifice of web socket support in my opinion. Do you have any ideas why `felix-http, war` features has been broken suddenly @mcollovati ?

**Comment by mcollovati** [comment]
As mentioned [here](https://github.com/vaadin/osgi/issues/90#issuecomment-1132919955) with felix-http and the war feature togheter there are port conflicts.
Previously `http` was used in place of `felix-http`, but this configuration did not work with Java 17, if I recall correctly.

**Comment by taefi** [comment]
I tried this out both with Java 11 and Java 17, with `karaf-maven-plugin:4.4.0` and `karaf-maven-plugin:4.3.7` (which supports Java 17 as well with overriding the version of `org.apache.felix.framework` to `7.0.3`) and could spot the following behaviour pattern:

When the whole application is built from scratch (`mvn clean install`) and main-ui is run (via `mvn -pl main-ui install -Prun`), at some point during the process, it downloads and run the karaf runtime inside the `main-ui/target/karaf` directory. Then it runs the following commands:
```
feature:install http war
feature:repo-add mvn:com.example/main-ui/1.0.0-SNAPSHOT/xml/features 
```
which results in creating a local cache from the 192 deployed and installed bundles under `./main-ui/target/karaf/data/cache` directory. This is obviously a time consuming task for the first time, and I was getting the same 404 error screen (mentioned by @mshabarov) while this was is going on. After this completes, you can refresh the page and see the application is running on http://localhost:8181.

From now on, if you stop and just rerun the application without performing a `clean install` this time, the application would be available exactly after you see the `[INFO] Artifact deployed` message in the terminal, which completely makes sense to me. 

I must admit that sometimes (once or twice in 10 times), after a build from scratch (caches cleared out), the karaf running process was not completing as it should, and it seems to be stuck at some point during that cache building process, since I could monitor the number of cache folders doesn't reach to 192 (with the current referenced bundles and dependencies) and it is not proceeding further no matter how much time you give it. At this point, re-running the project (without clean) would simply continue building the rest of the cache and results into a successfully running application. Rarely, I could also observe 404 error message even without a `clean install`, which obviously could be alleviated via a re-run as well.

I couldn't find any relationship between any possible anomaly of Vaadin platform and this behaviour so far. Also, could not spot any difference between the behaviour of `4.4.0` and `4.3.7` versions of `karaf-maven-plugin`.

**Comment by manolo** [comment]
Tried this again, and now I get this osgi error:

`Can't start container: Failed to add features to karaf: InvocationTargetException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=main-ui; type=karaf.feature; version="[1.0.0.SNAPSHOT,1.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=main-ui)(type=karaf.feature)(version>=1.0.0.SNAPSHOT)(version<=1.0.0.SNAPSHOT))" [caused by: Unable to resolve main-ui/1.0.0.SNAPSHOT: missing requirement [main-ui/1.0.0.SNAPSHOT] osgi.identity; osgi.identity=com.vaadin.flow.osgi; type=osgi.bundle; version="[8.0.2,8.0.2]"; resolution:=mandatory [caused by: Unable to resolve com.vaadin.flow.osgi/8.0.2: missing requirement [com.vaadin.flow.osgi/8.0.2] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.vaadin.pro.licensechecker)(version>=1.4.0)(!(version>=2.0.0)))"]]`

**Comment by mshabarov** [comment]
Tried with fresh starter using branch `v23` and both java 11 and 17:

git clone https://github.com/vaadin/vaadin-flow-karaf-example.git
cd vaadin-flow-karaf-example
change vaadin verison to `<vaadin.version>23.1.0.rc1</vaadin.version>`
mvn clean install
mvn -B -pl main-ui install -Prun
localhost:8181.

Works fine on my mac.
Did not tried with 23.0 however yet.

**Comment by mshabarov** [comment]
It doesn't work with 23.0.10 indeed.
23.0 is not compatible with the 8.0.2 because of license-checker.
with
```
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>flow-osgi</artifactId>
            <version>8.0.1</version>
        </dependency>
```
it works

**Comment by mshabarov** [comment]
Tested with platform `23.0.11` and it works.

**Comment by mcollovati** [comment]
Karaf feature list in `main-ui` seems to be incorrect and causes bind exceptions on port 8181, because of multiple services trying to listen on it

Following configuration seems to work
```
http-whiteboard,scr,spifly,${project.artifactId}
```

**Comment by mcollovati** [comment]
See #114

**Comment by manolo** [comment]
Is this still an issue? apparently it listens to 8181, although the project still does not work see: https://github.com/vaadin/vaadin-flow-karaf-example/issues/124
