### ISSUE TITLE
Designer not working with help-view type modules 

### ISSUE THREAD

**Issue by QNENet** [vaadin/base-starter-flow-karaf#12]
Right click help-view and select new>Vaadin 10+ design.

Design dialog reports

    No Polymer found in the project
    The project must have a valid polymer.html, wither from a webjar or from Bower
    Please check your project configuration.

In an earlier version, I think it was V14 compatibility, mode the designer worked through all modules to find the desired frontend.

**Comment by tanbt** [comment]
Since `help-view` module doesn't contain node_modules, Designer couldn't find related dependencies (e.g. Polymer).

To help Designer to know what module contains `node_modules`:

1. put `.vaadin/desinger/project-settings.json`  under the `help-view` module with this config
```
{
  "--node.modules.project.name": "project-base-karaf"
}
```
where `project-base-karaf` is the module with node_modules folder.

2. create an empty `frontend` folder under `help-view` module.

After these steps, you should be able to right click `help-view` and create a new V10+ design.
Example project: [base-starter-flow-karaf.zip](https://github.com/vaadin/base-starter-flow-karaf/files/6197087/base-starter-flow-karaf.zip)

**Comment by szolo** [comment]
Hello @QNENet,

I double-checked everything and you only need to use suggestion 1 from Tan. Everything will work afterwards and there is no need to create a separate `frontend` folder.
