### ISSUE TITLE
"Optional" view is removed if "Help" view is added after it

### ISSUE THREAD

**Issue by mstahv** [vaadin/base-starter-flow-karaf#14]
If you follow the instructions in readme file, the Optional appears in the menu, but is later removed when the help view is added.

**Comment by denis-anisimov** [comment]
The ticket doesn't contain the exact steps to reproduce and I'm absolutely happy to spend the time on writing the 
steps instead of you.
The only problem is : I cannot reproduce this with the latest changes in Flow so I cannot even say whether these
are the steps which you are using or I'm just guessing.

Steps to reproduce:
- checkout the project
- install all modules : run `mvn clean install` in the project
- make sure all three modules `greetservice-impl`, `help-view`  and `starter` are installed
- download Apache Karaf 4.3.x from here: https://karaf.apache.org/download.html
- unpack the distribution 
- run it via `./bin/karaf` 
- install HTTP whiteboard via interactive shell: `feature install http war` 
- add the starter project repo : `feature:repo-add mvn:com.example/project-base-karaf/1.0.0-SNAPSHOT/xml/features`
- start it: `feature:install project-base-karaf`
- install `greetservice-impl` bundle : `bundle:install mvn:com.example:greetservice-impl`
- start it : `bundle:start mvn:com.example:greetservice-impl`
- check in the browser that there is "Optional" menu item and optional view
- install `help-view` bundle : `bundle:install mvn:com.example/help-view/1.0.0-SNAPSHOT`
- start it : `bundle:start bundle:install mvn:com.example/help-view/1.0.0-SNAPSHOT`

The actual result is : optional view disappears

The expected result: optional view still presents along with help view.

There are a number of reasons why it's absolutely necessary to write all these steps + real result + expected result:
- it's not possible to say that there is a bug without steps to reproduce which can be used by anyone: my steps to reproduce doesn't allow to reproduce the issue
- it's not possible to say whether the issue is fixed or not without steps to reproduce
- absence of steps to reproduce requires some guessing (which can be wrong) from the person who is trying to work on the ticket which is extra useless work
- the person who is trying to to work on this ticket may be totally out of the context: it doesn't have to be me and the original description for someone who is not familiar with the project is cryptic.

I know that you are in hurry when you are writing the ticket and too lazy to provide all necessary information.
It's in contrast to me who has a lot of time to explain this to every ticket submitter and provide the steps to reproduce instead having them right away.

There is a reason why I'm asking all the time to make a ticket instead having conversation somewhere (e.g. in slack) : I need the exact details: exact steps to reproduce and the results. Such details always missed in every conversation and they may not be missed in the issue tracker : they are necessary. It just has no sense to copy the short report from Slack to the issue tracker.
