### ISSUE TITLE
Decouple OSGi service and api to standalone bundles

### ISSUE THREAD

**Issue by Maurice-Betzel** [vaadin/base-starter-flow-karaf#27]
I am not sure why the greeter api now is packaged with the base app, but any service should have it's own api bundle.
Please decouple the Greetservice, see:

https://github.com/Maurice-Betzel/base-starter-flow-karaf/tree/update-19.0.1

**Comment by mstahv** [comment]
You are right and we actually discussed it a while a back in the team that that would be the correct way to do it. But then again getting rid of that when starting to develop against your own service is bit more complicated than just deleting that one file, so we left it there at that point.

If you want to make a PR for that, you are welcome, otherwise we'll look into this later when working again with the example.

**Comment by mstahv** [comment]
This is now prepared in this branch:

https://github.com/vaadin/base-starter-flow-karaf/tree/feature/separate-api-module-for-greetservice

Based on v19 branch because master don't work for me ATM.
